DROP TABLE PRODTBL;
CREATE TABLE PRODTBL
(PRODCODE CHAR(3) NOT NULL,
PRODID CHAR(4) NOT NULL,
PRODDATE DATE NOT NULL,
PRODCUR CHAR(10) NULL
, CONSTRAINT PK_PRODTBL_PROCODE_PRODID PRIMARY KEY(PRODCODE, PRODID) --이렇게 CREATE문 안에서 설정가능하다.
);

ALTER TABLE PRODTBL --PRODTBL을 변경하자 
    ADD CONSTRAINT PK_PRODTBL_PROCODE_PRODID --추가할 제약 조건 이름은 'PK_PRODTBL_PROCODE_PRODID'이다.
    PRIMARY KEY(PRODCODE, PRODID); --기본 키 제약 조건이다(여기서 PRODCODE와 PRODID를 합침. 이러면 유일한 값이 될 수 있으므로 기본 키로 사용가능하다.)
    
    SELECT * FROM USER_CONSTRAINTS -- 키 정보가 등록된 테이블
    WHERE OWNER = 'TABLEDB' AND
        TABLE_NAME='USERTBL' AND
        CONSTRAINT_TYPE='P';