CREATE TABLE TBL1
(   A NUMBER(4) PRIMARY KEY,
    B NUMBER(4),
    C NUMBER(4)
);

SELECT I.INDEX_NAME, I.INDEX_TYPE, I.UNIQUENESS, C.COLUMN_NAME, C.DESCEND
FROM USER_INDEXES I
    INNER JOIN USER_IND_COLUMNS C
    ON I.INDEX_NAME = C.INDEX_NAME
WHERE I.TABLE_NAME='TBL1';

SELECT * FROM USER_INDEXES;
SELECT * FROM USER_IND_COLUMNS;

ALTER TABLE USERTBL --PK 제거하면서 관련된 FK도 제거
    DROP PRIMARY KEY CASCADE;
ALTER TABLE USERTBL -- PK생성
    ADD CONSTRAINT PK_USERTBL_USERID PRIMARY KEY(USERID);
ALTER TABLE BUYTBL --FK생성
    ADD CONSTRAINT FA_USERID_BUYTBL
    FOREIGN KEY (USERID)
    REFERENCES USERTBL(USERID);
    
SELECT * FROM USERTBL;

SELECT I.INDEX_NAME, I.INDEX_TYPE, I.UNIQUENESS, C.COLUMN_NAME, C.DESCEND
FROM USER_INDEXES I
    INNER JOIN USER_IND_COLUMNS C
    ON I.INDEX_NAME=C.INDEX_NAME
WHERE I.TABLE_NAME='USERTBL';

SELECT INDEX_NAME, LEAF_BLOCKS, DISTINCT_KEYS, NUM_ROWS FROM USER_INDEXES
    WHERE TABLE_NAME='USERTBL';

SELECT * FROM USERTBL WHERE USERID='BBK';
SELECT * FROM USERTBL WHERE USERNAME='바비킴';

CREATE INDEX IDX_USERTBL1_ADDR
ON USERTBL(ADDR);

CREATE UNIQUE INDEX IDX_USERTBL_USERNAME
ON USERTBL (USERNAME);

INSERT INTO USERTBL VALUES('GPS', '김범수', 1983, '미국', NULL, NULL, 162, NULL);

CREATE INDEX IDX_USERTBL_USERNAME_BIRTHYSER
ON USERTBL (USERNAME, BIRTHYEAR);
DROP INDEX IDX_USERTBL_USERNAME;

SELECT * FROM USERTBL WHERE USERNAME = '윤종신' AND BIRTHYEAR = '1969';
SELECT * FROM USERTBL WHERE USERNAME = '윤종신';

CREATE INDEX IDX_USERTBL_MIBILE1
ON USERTBL (MIBILE1);
SELECT * FROM USERTBL WHERE MIBILE1 = '011';

SELECT INDEX_NAME FROM USER_INDEXES
    WHERE TABLE_NAME='USERTBL';

DROP INDEX IDX_USERTBL1_ADDR;
DROP INDEX IDX_USERTBL_USERNAME_BIRTHYSER;
DROP INDEX IDX_USERTBL_MIBILE1;
DROP INDEX PK_USERTBL_USERID;

ALTER TABLE USERTBL
DROP PRIMARY KEY;


SELECT * FROM USER_CONSTRAINTS
WHERE OWNER='SQLDB' AND TABLE_NAME='BUYTBL' AND CONSTRAINT_TYPE='R';

ALTER TABLE USERTBL
DROP PRIMARY KEY CASCADE;