DROP USER SQLDB CASCADE;

CREATE USER SQLDB IDENTIFIED BY 1234
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;

GRANT CONNECT, RESOURCE, DBA TO SQLDB;

CREATE TABLE TBL1 (
A NUMBER(4) PRIMARY KEY,
B NUMBER(4),
C NUMBER(4)
);
SELECT * FROM TBL1;

SELECT I.INDEX_NAME, I.INDEX_TYPE, I.UNIQUENESS, C.COLUMN_NAME, C.DESCEND
FROM USER_INDEXES I
    INNER JOIN USER_IND_COLUMNS C
    ON I.INDEX_NAME = C.INDEX_NAME
WHERE I.TABLE_NAME = 'TBL2';

CREATE TABLE TBL2 (
A NUMBER(4) PRIMARY KEY,
B NUMBER(4) UNIQUE,
C NUMBER(4) UNIQUE,
D NUMBER(4)
);
SELECT * FROM TBL2;

CREATE TABLE BTREETBL
(USERID CHAR(8),
USERNAME NVARCHAR2(10)
);
INSERT INTO BTREETBL VALUES ('LSG', '이승기');
INSERT INTO BTREETBL VALUES ('KBS', '김범수');
INSERT INTO BTREETBL VALUES ('KKH', '김경호');
INSERT INTO BTREETBL VALUES ('JYP', '조용필');
INSERT INTO BTREETBL VALUES ('SSK', '성시경');
INSERT INTO BTREETBL VALUES ('LJB', '임재범');
INSERT INTO BTREETBL VALUES ('YJS', '윤종신');
INSERT INTO BTREETBL VALUES ('EJW', '은지원');
INSERT INTO BTREETBL VALUES ('JKW', '조관우');
INSERT INTO BTREETBL VALUES ('BBK', '바비킴');
SELECT * FROM BTREETBL;

SELECT ROWID, USERID, USERNAME FROM BTREETBL;

ALTER TABLE BTREETBL
ADD CONSTRAINT PK_BTREETBL_USERID
PRIMARY KEY (USERID);

INSERT INTO BTREETBL VALUES('FNT','푸니카');
INSERT INTO BTREETBL VALUES('KAI','카아이');