CREATE OR REPLACE VIEW V_USERBUYTBL
AS
SELECT U.USERID AS "USER ID", U.USERNAME AS "USER NAME", B.PRODNAME AS "PRODUCT NAME",
    U.ADDR, CONCAT(U.MOBILE1, U.MOBILE2) AS "MOBILE PHOEN"
    FROM USERTBL U
    INNER JOIN BUYTBL B
    ON U.USERID = B.USERID;

SELECT "USER ID", "USER NAME" FROM V_USERBUYTBL;

CREATE OR REPLACE VIEW V_USERBUYTBL
AS
SELECT U.USERID AS "사용자 아이디", U.USERNAME AS "이름", B.PRODNAME AS "제품 이름",
    U.ADDR, CONCAT(U.MOBILE1, U.MOBILE2) AS "전화번호"
    FROM USERTBL U
    INNER JOIN BUYTBL B
    ON U.USERID = B.USERID;
SELECT "사용자 아이디", "이름" FROM V_USERBUYTBL;

DROP VIEW V_USERBUYTBL;

CREATE OR REPLACE VIEW V_USERTBL
AS
SELECT USERID, USERNAME, ADDR FROM USERTBL;
SELECT * FROM USER_VIEWS;

UPDATE V_USERTBL SET ADDR = '부산' WHERE USERID= 'JKW';
INSERT INTO V_USERTBL(USERID, USERNAME, ADDR) VALUES('KBM', '김병만', '충북');

CREATE OR REPLACE VIEW V_USERTBL
AS
SELECT USERID, USERNAME, ADDR FROM USERTBL
WITH READ ONLY;

UPDATE V_USERTBL SET ADDR = '태국' WHERE USERID= 'SSK';

CREATE OR REPLACE VIEW V_SUM
AS
SELECT USERID, SUM(PRICE*AMOUNT) AS "TOTAL"
FROM BUYTBL GROUP BY USERID;

SELECT * FROM V_SUM;

INSERT INTO V_SUM VALUES('BAD', 1000);

CREATE OR REPLACE VIEW V_HEIGHT177
AS
SELECT * FROM USERTBL WHERE HEIGHT >= 177;
SELECT*FROM V_HEIGHT177;

DELETE FROM V_HEIGHT177 WHERE HEIGHT < 177;

INSERT INTO V_HEIGHT177 VALUES('KBM', '김병만', 1977, '경기', '010', '5555555', 158, '2019-01-01');

CREATE OR REPLACE VIEW V_HEIGHT177
AS
SELECT * FROM USERTBL WHERE HEIGHT >= 177
WITH CHECK OPTION;

INSERT INTO V_HEIGHT177 VALUES('WDT', '서장훈', 2006, '서울', '010', '3333333', 155, '2019-3-3');

CREATE TABLE BIGEMPLOYEES
(EMP_NO NUMBER(10) PRIMARY KEY,
BIRTH_DATE DATE NOT NULL,
FIRST_NAME VARCHAR(20) NOT NULL,
LAST_NAME VARCHAR(20) NOT NULL,
GENDER CHAR(1) NULL,
HIRE_DATE DATE NOT NULL);

select COUNT(*) FROM BIGEMPLOYEES;
SELECT * FROM BIGEMPLOYEES WHERE ROWNUM <=10;
