DROP TABLE BUYTBL;
DROP TABLE USERTBL;
CREATE TABLE USERTBL --회원 테이블
(USERID CHAR(8) NOT NULL, --사용자 아이디(PK)
USERNAME NVARCHAR2(10) , --이름
BIRTHYEAR NUMBER(4) , --출생년도
ADDR NCHAR(2) , --지역(2글자만 입력가능)
MOBILE1 CHAR(3) , --휴대폰 국번(010,011,017...)
MOBILE2 CHAR(8) , --휴대폰 나머지 전화번호
HEIGHT NUMBER(3), --키
MDATE DATE --회원 가입일
);
CREATE TABLE BUYTBL --구매 테이블
(IDNUM NUMBER(8) PRIMARY KEY, --순번
USERID CHAR(8) ,--아이디
PRODNAME NCHAR(6) , --물품명
GROUPNAME NCHAR(4) , --분류
PRICE NUMBER(8), -- 단가
AMOUNT NUMBER(3) --수량
);
DROP SEQUENCE IDSEQ;
CREATE SEQUENCE IDSEQ;
DROP TABLE USERTBL;
INSERT INTO USERTBL VALUES('LSG', '이승기', 1987, '서울', '011', '11111111', 182, '2008-8-8');
INSERT INTO USERTBL VALUES('KBS', '김범수', NULL, '경남', '011', '22222222', 173, '2012-4-4');
INSERT INTO USERTBL VALUES('KKH', '김경호', 1871, '전남', '019', '33333333', 177, '2007-7-7');
INSERT INTO USERTBL VALUES('JYP', '조용필', 1950, '경기', '011', '44444444', 166, '2009-4-4');
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'KBS', '운동화', NULL, 30, 2);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'KBS', '노트북', '전자', 1000, 1);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'JYP', '모니터', '전자', 200, 1);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'BBK', '모니터', '전자', 200, 5);
--STEP6
INSERT INTO USERTBL VALUES('SSK', '성시경', 1979, '서울', NULL, NULL, 186, '2013-12-12');
INSERT INTO USERTBL VALUES('LJB', '임재범', 1963, '서울', '016', '66666666', 182, '2009-9-9');
INSERT INTO USERTBL VALUES('YJS', '윤종신', 1969, '경남', NULL, NULL, 174, '2005-5-5');
INSERT INTO USERTBL VALUES('EJW', '은지원', 1972, '경북', '011', '88888888', 166, '2009-4-4');
INSERT INTO USERTBL VALUES('JKW', '조관우', 1965, '경기', '018', '99999999', 177, '2007-7-7');
INSERT INTO USERTBL VALUES('BBK', '바비킴', 1973, '서울', '010', '00000000', 166, '2009-4-4');



ALTER TABLE USERTBL--기본 키 제약조건을 생성
    ADD CONSTRAINT PK_USERTBL_USERID
    PRIMARY KEY (USERID);
    
SELECT * FROM USER_CONSTRAINTS--DESCRIBE문으로 확인하면 USERID열이 NOT NULL로 설정된 것을 확인할 수 있다
    WHERE OWNER = 'TABLEDB' AND TABLE_NAME='USERTBL' AND CONSTRAINT_TYPE='P';
    DESCRIBE USERTBL;
    
DELETE FROM BUYTBL WHERE USERID ='BBK';    
ALTER TABLE BUYTBL
    ADD CONSTRAINT FK_USERTBL_BUYTBL
    FOREIGN KEY (USERID)
    REFERENCES USERTBL (USERID);
    
ALTER TABLE BUYTBL
    DISABLE CONSTRAINT FK_USERTBL_BUYTBL;
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'BBK', '모니터', '전자', 200, 5);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'KBS', '청바지', '의류', 50, 3);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'BBK', '메모리', '전자', 80, 10);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'SSK', '책', '서적', 15, 5);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'EJW', '책', '서적', 15, 2);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'EJW', '청바지', '의류', 50, 1);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'BBK', '운동화', NULL, 30, 2);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'EJW', '책', '서적', 15, 1);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'BBK', '운동화', NULL, 30, 2);
ALTER TABLE BUYTBL
    ENABLE NOVALIDATE CONSTRAINT FK_USERTBL_BUYTBL;
    
ALTER TABLE USERTBL
    ADD CONSTRAINT CK_BIRTHYEAR
    CHECK (BIRTHYEAR >= 1900 AND BIRTHYEAR<=2017)
    ENABLE NOVALIDATE;
    
insert into userTBL values('SSK', '성시경', 1979, '서울', null, null, 186, '2013-12-12');
insert into userTBL values('LJB', '임재범', 1963, '서울', '016', '66666666', 182, '2009-9-9');
insert into userTBL values('YJS', '윤종신', 1969, '경남', null, null, 170, '2005-5-5');
insert into userTBL values('EJW', '은지원', 1972, '경북', '011', '88888888', 174, '2014-3-3');
insert into userTBL values('JKW', '조관우', 1965, '경기', '018', '99999999', 172, '2010-10-10');
insert into userTBL values('BBK', '바비킴', 1973, '서울', '010', '00000000', 176, '2013-5-5');

DELETE FROM USERTBL WHERE USERID = 'BBK';

ALTER TABLE BUYTBL
    DROP CONSTRAINT FK_USERTBL_BUYTBL;
ALTER TABLE BUYTBL
    ADD CONSTRAINT FK_USERTBL_BUYTBL
        FOREIGN KEY (USERID)
        REFERENCES USERTBL (USERID)
        ON DELETE CASCADE;
        
DELETE FROM USERTBL WHERE USERID = 'BBK';
SELECT * FROM BUYTBL;

ALTER TABLE USERTBL
    DROP COLUMN BIRTHYEAR;
    
SELECT USERID, USERNAME, ADDR FROM USERTBL;

CREATE VIEW V_USERTBL
AS
SELECT USERID, USERNAME, ADDR FROM USERTBL;
SELECT * FROM V_USERTBL;

CREATE OR REPLACE VIEW V_USERTBL
AS
SELECT U.USERID, U.USERNAME, B.PRODNAME, U.ADDR, U.MOBILE1 || U.MOBILE2 AS "연락처"
FROM USERTBL U
INNER JOIN BUYTBL B
ON U.USERID=B.USERID;

SELECT * FROM V_USERTBL WHERE USERNAME = '김범수';
