CREATE USER MUSIC IDENTIFIED BY 1234
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP;
    
GRANT CONNECT, RESOURCE, DBA TO MUSIC;

CREATE TABLE 앨범
(앨범번호 VARCHAR2(3) NOT NULL PRIMARY KEY,
타이틀 VARCHAR2(30) NOT NULL,
아티스트 VARCHAR2(30),
가격 NUMBER,
발매일 DATE,
배급 VARCHAR2(30),
별점 NUMBER(3,1)
);
CREATE TABLE 곡
(앨범번호 VARCHAR2(3) NOT NULL PRIMARY KEY 
디스크 VARCHAR2(3)
곡번호 VARCHAR2(3)
곡명 VARCHAR2(50)
구분 VARCHAR2(10)
);