DROP TABLE USERTBL CASCADE CONSTRAINTS;
CREATE TABLE USERTBL --회원 테이블
(USERID CHAR(8) NOT NULL CONSTRAINT PK_USERTBL_USERTBL_USERID PRIMARY KEY, --사용자 아이디(PK)
USERNAME NVARCHAR2(10) NOT NULL, --이름
BIRTHYEAR NUMBER(4) NOT NULL, --출생년도
ADDR NCHAR(2) NOT NULL, --지역(2글자만 입력가능)
MOBILE1 CHAR(3) NULL, --휴대폰 국번(010,011,017...)
MOBILE2 CHAR(8) NULL, --휴대폰 나머지 전화번호
HEIGHT NUMBER(3) NULL, --키
MDATE DATE NULL--회원 가입일
, CONSTRAINT PK_USERTBL_USERTBL_USERID PRIMARY KEY(USERID)--여기서 CONSTRAINT는 생략가능, 기본 키의 이름을 지정할 필요없다면 마지막 행에 간단히 PRIMARY(USERID)문만 써줘도 된다
);
SELECT * FROM USER_CONSTRAINTS -- 키 정보가 등록된 테이블
    WHERE OWNER = 'TABLEDB' AND
        TABLE_NAME='USERTBL' AND
        CONSTRAINT_TYPE='P';

CREATE TABLE BUYTBL --구매 테이블
(IDNUM NUMBER(8) NOT NULL PRIMARY KEY, --순번
USERID CHAR(8) NOT NULL,--아이디
PRODNAME NCHAR(6) NOT NULL, --물품명
GROUPNAME NCHAR(4) NULL, --분류
PRICE NUMBER(8) NULL, -- 단가
AMOUNT NUMBER(3) NOT NULL --수량
,FOREIGN KEY(USERID) REFERENCES USERTBL(USERID) --이 테이블(BUYTBL)의 USERID열과 USERTBL테이블의 USERID열과 외래 키 관계를 맺어라란 뜻
);

INSERT INTO USERTBL VALUES('LSG', '이승기', 1987, '서울', '011', '11111111', 182, '2008-8-8');
INSERT INTO USERTBL VALUES('KBS', '김범수', 1979, '경남', '011', '22222222', 173, '2012-4-4');
INSERT INTO USERTBL VALUES('KKH', '김경호', 1971, '전남', '019', '33333333', 177, '2007-7-7');
INSERT INTO USERTBL VALUES('JYP', '조용필', 1961, '대구', '011', '44444444', 165, '2015-6-6');

INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'KBS', '운동화', NULL, 30, 2);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'KBS', '노트북', '전자', 1000, 1);
INSERT INTO BUYTBL VALUES(IDSEQ.NEXTVAL, 'JYP', '모니터', '전자', 200, 1);